name: Deploy to Dropbox
uses: aTable/deploy-to-dropbox@v1.0.7

on:
  push:
    branches:
      - master

jobs:
  local_development:
    runs-on: ubuntu-latest
    name: Upload
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Execute my action
        uses: ./ # Uses an action in the root directory
        with:
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          DROPBOX_DESTINATION_PATH_PREFIX: "/"
          GLOB: "*/**/*.org"
          DEBUG: false
